### ISSUE TITLE
Gems look like trees and spiders in DF 0.40.24

### ISSUE THREAD

**Issue by blackjack** [DFgraphics/Ironhand#1]
Hi! I faced a problem described in a title: gem veins look like forests and spider caves :) 
![2015-05-07 19 45 12](https://cloud.githubusercontent.com/assets/221255/7521909/d0365e5a-f4f1-11e4-9ff6-519486b84dd9.png)

Can you help me?

**Comment by fricy** [comment]
Looks like a raw mismatch, how did you install the tileset? Did you overwrite the ASCII raws with the Ironhand raws before generating the world? Or are you loading a save without updating the save raws maybe?  
General advice: Use one of the [Starter Packs](http://lazynewbpack.com/), as those are designed to help with newbie problems, or use a [launcher](https://bitbucket.org/Pidgeot/python-lnp/downloads) to install tilesets.

**Comment by blackjack** [comment]
I uncompressed an update pack from http://dffd.bay12games.com/file.php?id=8747 to the LNP/graphics/Ironhand and installed it with "Install Graphics" from PyLNP
PyLNP was downloaded from http://www.lazynewbpack.com/linux/

Anyway, I think I'll just stick to Phoebus graphics then

**Comment by fricy** [comment]
Ok, I can more-or-less reproduce the problem. You need to say yes, when the launcher asks you if you want to update the saves, otherwise you'll get Phoebus raws with Ironhand tile mappings in your existing saves.

**Comment by blackjack** [comment]
It looks like PyLNP v.0.40.23 R3 savegame update is broken. I used previous version of PyLNP and everything worked as intended. I hope it will help soneone.
